apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-pv-volume
  labels:
    type: local
spec:
  storageClassName: ceph-manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  hostPath:
    path: "/mnt/ceph-rbd1"
