apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f readwritetxtfile.yml --chart --controller deployment
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: db-mysql
  name: db-mysql
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f readwritetxtfile.yml --chart --controller
          deployment
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: db-mysql
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: mysql
        - name: MYSQL_PASSWORD
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: test
        - name: MYSQL_USER
          value: test
        image: mysql
        name: db-mysql
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
