apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.TELEMETRY_AGENT_NAMESPACE}}       
##############################
#    for internal access
##############################

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry
  namespace: {{.Values.TELEMETRY_AGENT_NAMESPACE}}  
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: telemetry
subjects:
- kind: ServiceAccount
  name: telemetry
  namespace: {{.Values.TELEMETRY_AGENT_NAMESPACE}}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
  
  
############################ 
#   For external Client  
############################
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-user
  namespace: {{.Values.TELEMETRY_AGENT_NAMESPACE}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.TELEMETRY_AGENT_NAMESPACE}}
  name: telemetry-user-role
rules:
  - apiGroups: ["*"]
    resources: ["services/proxy"] 
    #resourceNames: ["telemetry-agent-service","http:telemetry-agent-service:"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: telemetry-user
subjects:
- kind: ServiceAccount
  name: telemetry-user
  namespace: {{.Values.TELEMETRY_AGENT_NAMESPACE}}
roleRef:
  kind: Role
  name: telemetry-user-role
