kind: Service
apiVersion: v1
metadata:
  name: {{.Values.TELEMETRY_SERVICE_NAME}}
  namespace: {{.Values.TELEMETRY_AGENT_NAMESPACE}}
  labels:
    belongsToApp: {{.Values.BELONGS_TO_APP}}
spec:
  selector:
    app: {{.Values.TELEMETRY_AGENT_SELECTOR_APP_NAME}}
  ports:
  - protocol: {{.Values.PROTOCOL}}
    port: {{.Values.TELEMETRY_NODE_PORT}}
    targetPort: {{.Values.TELEMETRY_CONTAINER_PORT}}
